name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: |
          set -o pipefail
          mkdir -p ./pr
          echo ${{ github.event.number }} | tee ./pr/number
          yarn all |& tee ./pr/all_result
      - uses: actions/upload-artifact@v3
        if: ${{ github.event_name == 'pull_request' && (success() || failure()) }}
        with:
          name: all
          path: pr/
